export const browserCoreExamples = [
  "legalogy browser status",
  "legalogy browser start",
  "legalogy browser stop",
  "legalogy browser tabs",
  "legalogy browser open https://example.com",
  "legalogy browser focus abcd1234",
  "legalogy browser close abcd1234",
  "legalogy browser screenshot",
  "legalogy browser screenshot --full-page",
  "legalogy browser screenshot --ref 12",
  "legalogy browser snapshot",
  "legalogy browser snapshot --format aria --limit 200",
  "legalogy browser snapshot --efficient",
  "legalogy browser snapshot --labels",
];

export const browserActionExamples = [
  "legalogy browser navigate https://example.com",
  "legalogy browser resize 1280 720",
  "legalogy browser click 12 --double",
  'legalogy browser type 23 "hello" --submit',
  "legalogy browser press Enter",
  "legalogy browser hover 44",
  "legalogy browser drag 10 11",
  "legalogy browser select 9 OptionA OptionB",
  "legalogy browser upload /tmp/legalogy/uploads/file.pdf",
  'legalogy browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "legalogy browser dialog --accept",
  'legalogy browser wait --text "Done"',
  "legalogy browser evaluate --fn '(el) => el.textContent' --ref 7",
  "legalogy browser console --level error",
  "legalogy browser pdf",
];
